export default [
  {
    id: 1,
    name: "Ashar Akram",
    location: "Lahore",
    email: "alicia.rivera@example.com",
    phone: "(459) 239-2229",
    isContact: false,
  },
  {
    id: 2,
    name: "Mohsin Nawaz",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: false,
  },
  {
    id: 3,
    name: "Ahsan Rana",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: false,
  },
  {
    id: 4,
    name: "Zameet khalid",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: false,
  },
  {
    id: 5,
    name: "Anas Akram",
    location: "Islamabad",
    email: "anasakram@example.com",
    phone: "(977) 915-0667",
    isContact: false,
  },
  {
    id: 6,
    name: "Muhammad Ali",
    location: "Karachi",
    email: "ali@example.com",
    phone: "(977) 915-0667",
    isContact: false,
  },
];
